# Generated by Django 4.2.30 on 2026-05-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('dsa', 'Data Structures & Algorithms'), ('system_design', 'System Design'), ('hr', 'HR & Behavioural'), ('core_cs', 'Core CS'), ('mixed', 'Mixed')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('company', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft'), ('amazon', 'Amazon'), ('flipkart', 'Flipkart'), ('zomato', 'Zomato'), ('razorpay', 'Razorpay'), ('tcs', 'TCS'), ('infosys', 'Infosys'), ('wipro', 'Wipro'), ('startup', 'Generic Startup'), ('general', 'General')], default='general', max_length=20)),
                ('model_answer', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('times_asked', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'difficulty'],
            },
        ),
    ]
