# Generated by Django 4.2.30 on 2026-05-10 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_interviews', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('best_score', models.FloatField(default=0)),
                ('weak_topics', models.JSONField(default=list)),
                ('strong_topics', models.JSONField(default=list)),
                ('scores_history', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0)),
                ('technical_score', models.FloatField(default=0)),
                ('communication_score', models.FloatField(default=0)),
                ('strong_topics', models.JSONField(default=list)),
                ('weak_topics', models.JSONField(default=list)),
                ('detailed_feedback', models.TextField(blank=True)),
                ('improvement_tips', models.JSONField(default=list)),
                ('question_breakdown', models.JSONField(default=list)),
                ('total_questions_asked', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='interviews.interviewsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
