# Generated by Django 4.2.30 on 2026-05-10 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('dsa', 'Data Structures & Algorithms'), ('system_design', 'System Design'), ('hr', 'HR & Behavioural'), ('core_cs', 'Core CS (OS, DBMS, Networks)'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('target_company', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft'), ('amazon', 'Amazon'), ('flipkart', 'Flipkart'), ('zomato', 'Zomato'), ('razorpay', 'Razorpay'), ('tcs', 'TCS'), ('infosys', 'Infosys'), ('wipro', 'Wipro'), ('startup', 'Generic Startup'), ('general', 'General')], default='general', max_length=20)),
                ('total_questions', models.IntegerField(default=10)),
                ('questions_asked', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('interviewer', 'Interviewer'), ('candidate', 'Candidate'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interviews.interviewsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
